#' IMPACT files
#'
#' URLs to annotations/LD-scores generated by
#' \href{https://github.com/immunogenomics/IMPACT}{IMPACT}
#' (Inference and Modeling of Phenotype-related ACtive Transcription).
#' @family IMPACT
#' @source
#' \code{
#' IMPACT_files <- downloadR::zenodo_list(token = token)[!endsWith(filename,
#'                                                      c(".zip",".tbi")),]
#' usethis::use_data(IMPACT_files, overwrite = TRUE)
#' }
#' @usage data("IMPACT_files")
"IMPACT_files"
